#user nginx;
user www-data;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # ==========================================
    # HARDENING 1: Matikan Server Tokens
    # ==========================================
    # Menyembunyikan versi Nginx pada halaman error dan HTTP Header
    server_tokens off;

    # ==========================================
    # HARDENING 2: Rate Limiting (Maks 5 req/detik)
    # ==========================================
    # Menyiapkan memori zona sebesar 10MB (bisa menampung ~160.000 IP) 
    # bernama "one" untuk membatasi request berdasarkan IP asal ($binary_remote_addr)
    limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;

    # Logging & Optimasi Standar
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    sendfile on;
    keepalive_timeout 65;

    # Masukkan konfigurasi spesifik dari folder conf.d
    #include /etc/nginx/conf.d/*.conf;
    # Masukkan konfigurasi spesifik dari folder conf.d proyek lab
    include /home/aradea/dev/devops-production-labs/local-infrastructure-hardening/nginx/conf.d/*.conf;
}
