limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;
server {
    listen       80;
    server_name  localhost;
    # Pengalihan otomatis dari HTTP (80) ke HTTPS (443)
    return 301 https://$host$request_uri;
}
server {
    # ==========================================
    # AKTIFKAN PORT 443 (HTTPS / SSL)
    # ==========================================
    listen       443 ssl;
    server_name  localhost;

    # Path absolut menuju sertifikat yang baru kita buat
    #ssl_certificate      /home/aradea/dev/devops-production-labs/local-infrastructure-hardening/nginx/certs/localhost+1.pem;
    #ssl_certificate_key  /home/aradea/dev/devops-production-labs/local-infrastructure-hardening/nginx/certs/localhost+1-key.pem;

    ssl_certificate     /etc/nginx/certs/localhost+1.pem;
    ssl_certificate_key /etc/nginx/certs/localhost+1-key.pem;	
	
    # Optimasi keamanan SSL standar
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_ciphers          HIGH:!aNULL:!MD5;
	
    # ==========================================
    # HARDENING 3: Pasang Security Headers
    # ==========================================
    # Mencegah website di-frame orang lain (Anti-Clickjacking)
    add_header X-Frame-Options "SAMEORIGIN" always;
    
    # Mengaktifkan proteksi XSS bawaan pada beberapa browser lama
    add_header X-XSS-Protection "1; mode=block" always;
    
    # Mencegah browser menebak-nebak tipe file (Anti-MIME Sniffing)
    add_header X-Content-Type-Options "nosniff" always;
    
    # Membatasi informasi referrer yang dikirim ke situs lain
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    
    # Mengontrol fitur browser apa saja yang boleh aktif (Content Security Policy dasar)
    add_header Content-Security-Policy "default-src 'self'; http: https: data: blob: 'unsafe-inline'" always;

    location / {
        # ==========================================
        # HARDENING 4: Terapkan Rate Limiting
        # ==========================================
        # Menggunakan zona "one" yang sudah dibuat di nginx.conf
        # burst=5 artinya memberikan toleransi antrean tambahan sebanyak 5 request
        # nodelay artinya request yang masuk toleransi langsung diproses tanpa ditunda
        limit_req zone=one burst=5 nodelay;

	# Ganti root & index menjadi proxy_pass ke nama container API Anda
        proxy_pass http://api-server:8080;

        # Oper informasi header asli client ke backend Node.js
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        #root   /usr/share/nginx/html;
        #index  index.html index.htm;
    }

    # Custom halaman error jika terkena Rate Limit (HTTP 503)
    error_page 503 /custom_503.html;
    location = /custom_503.html {
        return 503 "Waduh! Terlalu banyak request. Santai sejenak ya (Rate Limit Terlampaui).\n";
    }
}
