services:
  # ==========================================
  # 1. FRONTEND SERVICE (Nginx Reverse Proxy)
  # ==========================================
  frontend:
    image: nginx:alpine
    container_name: frontend-app
    ports:
      - "8080:80"
    # HANYA terhubung ke jaringan frontend
    networks:
      - frontend-net
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'      # Batasi maksimal 25% dari 1 Core CPU
          memory: 128M      # Batasi maksimal 128MB RAM
    restart: unless-stopped

  # ==========================================
  # 2. BACKEND SERVICE (Secure Node.js API)
  # ==========================================
  backend:
    build: .
    image: awesome-backend:production
    container_name: backend-api
    ports:
      - "3000:3000"
    # TERBUNGKUS DI DUA JARINGAN: jembatan ke frontend dan jembatan ke database
    networks:
      - frontend-net
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '0.50'      # Batasi maksimal 50% dari 1 Core CPU (Aplikasi inti)
          memory: 256M      # Batasi maksimal 256MB RAM
    # Strategi Self-Healing (Menggunakan IP internal 127.0.0.1)
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "-e", "require('http').get('http://127.0.0.1:3000/api/v1/mock', (res) => { if (res.statusCode === 200) process.exit(0); else process.exit(1); })"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # ==========================================
  # 3. DATABASE SERVICE (Redis Cache Storage)
  # ==========================================
  database:
    image: redis:alpine
    container_name: database-storage
    # HANYA terhubung ke data-net (Terisolasi total dari internet & frontend)
    networks:
      - data-net
    deploy:
      resources:
        limits:
          cpus: '0.25'      # Batasi maksimal 25% dari 1 Core CPU
          memory: 128M      # Batasi maksimal 128MB RAM
    restart: unless-stopped

# ==========================================
# DEFINISI 3 NETWORK BRIDGE TERISOLASI
# ==========================================
networks:
  frontend-net:
    driver: bridge
    name: net_frontend_tier
  backend-net:
    driver: bridge
    name: net_backend_tier
  data-net:
    driver: bridge
    name: net_data_tier